- name: Install Dependencies
        run: npm install --legacy-peer-deps
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # Aquí usamos la versión más reciente

      - name: Instalar y Construir
        run: |
          npm install
          npm run build
